### ISSUE TITLE
Don't load them all at once!

### ISSUE THREAD

**Issue by Onktebong** [sienori/Tab-Session-Manager#248] opened 2018-05-06 14:21 UTC
Hi,
I'm using the current Firefox with the current Tab Session Manager.
Instead of just loading my session, something happened, and now TSM seems to be loading or updating all the tabs at startup at the same time. This is causing my entire system to grind to a halt.
Here is an example of an URL TSM is trying to load:
moz-extension://a7920983-b583-474b-a512-597e64ed4ee8/replaced/replaced.html?state=redirect&title=William%20Whitaker%27s%20Words&url=http%3A//archives.nd.edu/cgi-bin/wordz.pl%3Fkeyword%3Dirrumatio&favIconUrl=undefined
Is there any way to get my old session back and working like before?
Thank you.

**Comment by sienori** [comment] 2018-05-13 07:48
I'm sorry, but I don't understand you. 
Please tell me the values ​​of the following settings.
* Tab lazy loading
* Restore previous session at startup

**Comment by nollinvoyd** [comment] 2018-07-04 23:14
I seem to be having similar problem as the OP, and another that may be related.

Even tho I have both "Tab lazy loading" and "Restore previous session at startup" selected, all my tabs load when I launch Firefox..

The next problem randomly occurred In the past several weeks that I've been using Quantum.  I decided to post in this thread because that URL posted by the OP is suspiciously similar to what I have been experiencing.

I get multiple unloaded or unloadable tabs. What I mean by that is when you select these tabs, sometimes you get the page, and sometimes you don't.  I've attached examples.

A typical example of an unloadable tab is they all have the same address prefix, which is partially displayed in the tab title, i.e. this is the about:addon page that didn't load, and below two attachments of what the page looks like on different occasions.

moz-extension://914d076a-3759-4362-99f6-33bbb869bc9c/replaced/replaced.html?state=open_faild&title=914d076a-3759-4362-99f6-33bbb869bc9c/replaced/replaced.html%3Fstate%3Dredirect%26title%3DAdd-ons%2520Manager%26url%3Dabout%253Aaddons%26favIconUrl%3Dchrome%253A%252F%252Fmozapps%252Fskin%252Fextensions%252FextensionGeneric-16.svg&url=about%3Aaddons&favIconUrl=undefined

Below those 2 images, examples of how the tabs appear. The fourth image is a tab that loaded when it was individually selected. That's the thing, some load, some don't,

After it happened today, I restored a session from yesterday that had very similar data, and it was fine. 

The first time it happened,  "Auto Tab Discard", and I thought it was to blam, so I switched to "Unload Tabs", but it still occurs.  

![image about 1](https://user-images.githubusercontent.com/20844322/42295991-1328e49e-7fa5-11e8-8571-17ec430094bd.png)

![image about 2](https://user-images.githubusercontent.com/20844322/42295994-1e1ea14a-7fa5-11e8-8c5a-635b8f012a5b.png)

![image1-tabbar](https://user-images.githubusercontent.com/20844322/42295997-2542c8d4-7fa5-11e8-84d3-4710d37317a2.png)

![image2 about tabbar](https://user-images.githubusercontent.com/20844322/42295999-2cc13708-7fa5-11e8-909d-5e9fe95f4386.png)

![image3 dropdown](https://user-images.githubusercontent.com/20844322/42296000-33836e12-7fa5-11e8-83bf-5df1d8816fc7.png)

![image3](https://user-images.githubusercontent.com/20844322/42296002-3970de04-7fa5-11e8-8668-7d65de8195ff.png)

![image4loaded](https://user-images.githubusercontent.com/20844322/42296007-3fca84d0-7fa5-11e8-9fe4-0d2c4427cc32.png)

![image5unloaded](https://user-images.githubusercontent.com/20844322/42296009-49719e6a-7fa5-11e8-920e-7340f2d6d8f9.png)

![tabs new](https://user-images.githubusercontent.com/20844322/42296012-4fe27a08-7fa5-11e8-9e39-c2cf4971a0cc.png)

**Comment by 1RonRock** [comment] 2018-07-05 13:38
I get the same on a Firefox startup often.

**Comment by nollinvoyd** [comment] 2018-07-06 21:31
**Update**

I will preface my remarks by saying I just stumbled upon this about 15 minutes ago, so I can't say the bad 
behavior wont return.

I was making some settings adjustments to Tab-Session-Manager in an attempt to improve the situation,  and I discovered several notable results that when I unchecked "Restore previous session at startup".

All the behavior previously described seems to have changed.  

All the tabs are **not** loaded at startup, only the focused tab.

No **unloadeable/broken** tabs.

Even tho I have disabled "Restore previous session at startup", the previous session still loads at startup.

This was the experience I was expecting/hoping for when I chose Tab-Session-Manager

**Comment by sienori** [comment] 2018-07-07 06:55
@nollinvoyd 
> Even tho I have disabled "Restore previous session at startup", the previous session still loads at startup.

You seem to be turning on [`Restore previous session`](https://support.mozilla.org/en-US/kb/restore-previous-session#w_configuring-session-restore) of firefox standard function.

**Comment by nollinvoyd** [comment] 2018-07-07 19:35
Hello sienori,

First. let me say I value this extension.  It does an important job.  Thank you.

Please re-read my previous posts.  

- I understand the Firefox default "restore previous session" function.

- I **"want"** the previous session to be restored.  That's why I originally enabled the Firefox default "restore previous session" option.

- The **"problem"** is that Tab Session Manager "**breaks**", in the way I have described, when **"Restore previous session at startup"** in the Tab Session Manager options is enabled.

Now that I have disabled **"Restore previous session at startup"** in the Tab Session Manager options, I can still have the previous session restored, but it is not exhibiting all the bad symptoms I described in the previous posts.

**Comment by sienori** [comment] 2018-07-08 06:40
@nollinvoyd 
Thank you for telling me the main points.

Does "Tab Session Manager breaks" mean that `This page can not be opened by Tab Session Manager` is displayed?
This message is displayed when opening a special page.
For example, `about:addons`, `about:debugging`, and local page.
It is **impossible** to open these pages due to limitations of WebExtensions.
Therefore, it is not a bug that you can not open those pages.
Thanks for your understanding.

**Comment by sienori** [comment] 2018-10-28 17:47
I fixed the problem that increased memory usage when restoring session or closing a large number of tabs. 90390af
Also, I added option to use "discarded" property for lazy loading. 45719c3
Enabling this option will improve performance when opening tabs.

**Closed** 2018-11-08 13:19 UTC
Labels: bug, solved
