### ISSUE TITLE
Out of memory/huge memory usage when restoring session

### ISSUE THREAD

**Issue by ponarC** [sienori/Tab-Session-Manager#249] opened 2018-05-07 17:07 UTC
TSM 3.1.1
Firefox 59.0.2
Linux Mint
Session with18 windows and 831 tabs (file: 20MB) (less are problematic too)

Often when i try restore last session, ff create all tabs and get very slow (it's unable to load active tabs). One thread consume 100% cpu and memory usage slowly grow reaching huge value above 30GB causing OOM or manual kill when issue is recognized. Sometimes restoring is successful - fast, without 100% and no memory consume or with very small memory overhead.

Last time i got 16GB memory peak with successful restore, then memory usage drop to reasonable 1GB. This allow me to run about:memory between successful restoring and memory drop.

Report show that 10GB is allocated by TSM.

11,436.85 MB (100.0%) -- explicit
├──10,493.84 MB (91.75%) -- add-ons
│  ├──10,487.74 MB (91.70%) -- Tab-Session-Manager@sienori/window-objects/top(moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/_generated_background_page.html, id=13)
│  │  ├───6,101.16 MB (53.35%) -- active/window(moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/_generated_background_page.html)
│  │  │   ├──6,100.94 MB (53.34%) -- js-compartment(moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/_generated_background_page.html)
│  │  │   │  ├──6,100.59 MB (53.34%) -- classes
│  │  │   │  │  ├──6,095.92 MB (53.30%) -- class(Object)/objects
│  │  │   │  │  │  ├──5,125.00 MB (44.81%) -- malloc-heap
│  │  │   │  │  │  │  ├──3,891.99 MB (34.03%) ── slots
│  │  │   │  │  │  │  └──1,233.00 MB (10.78%) ── elements/normal
│  │  │   │  │  │  └────970.92 MB (08.49%) ── gc-heap
│  │  │   │  │  └──────4.67 MB (00.04%) ++ (9 tiny)
│  │  │   │  └──────0.35 MB (00.00%) ++ (5 tiny)
│  │  │   └──────0.22 MB (00.00%) ++ (3 tiny)
│  │  └───4,386.58 MB (38.35%) -- js-zone(0x7f13edffe000)
│  │      ├──3,390.25 MB (29.64%) -- strings
│  │      │  ├──2,754.86 MB (24.09%) ++ (2269 tiny)
│  │      │  ├────243.28 MB (02.13%) ── string(length=15, copies=10629069, "firefox-default")/gc-heap/latin1
│  │      │  ├────242.93 MB (02.12%) ── string(length=8, copies=10613831, "complete")/gc-heap/latin1
│  │      │  └────149.17 MB (01.30%) -- string(length=71, copies=1504044, "moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/replaced/undefined")
│  │      │       ├──114.75 MB (01.00%) ── malloc-heap/latin1
│  │      │       └───34.42 MB (00.30%) ── gc-heap/latin1
│  │      ├────958.44 MB (08.38%) ── unused-gc-things
│  │      └─────37.89 MB (00.33%) ++ (11 tiny)
│  └───────6.10 MB (00.05%) ++ (10 tiny)
├─────282.56 MB (02.47%) -- heap-overhead
│     ├──172.06 MB (01.50%) ── bookkeeping
│     └──110.50 MB (00.97%) ++ (2 tiny)
├─────178.19 MB (01.56%) ++ (25 tiny)
├─────175.75 MB (01.54%) -- gfx
│     ├──175.32 MB (01.53%) ── heap-textures
│     └────0.43 MB (00.00%) ++ (5 tiny)
├─────159.78 MB (01.40%) ++ js-non-window
└─────146.73 MB (01.28%) ++ window-objects

**Comment by grahamperrin** [comment] 2018-05-08 17:53
I found the same symptoms recently with Firefox 60 (maybe 60.0_1,1) on FreeBSD-CURRENT. 

At the time, Firefox was almost certainly coincidentally affected by Mozilla bug [944918 - indexedDB broken - UnknownError - Error opening Database](https://bugzilla.mozilla.org/show_bug.cgi?id=944918). Worked around in my case by removing `.directory` files from all subdirectories of the `storage` directory …

… time, now, for me to tell whether symptoms of this issue 249 are reproducible.

**Comment by grahamperrin** [comment] 2018-05-08 19:38
1,190 tabs across fifteen windows: restored in thirteen minutes, which is probably about right in my environment. Memory usage: normal. A frame from a screen recording: 

![2018-05-08 20 29 23 frame](https://user-images.githubusercontent.com/192271/39778957-ab7aae30-52ff-11e8-9fe6-57825054467b.png)

**Comment by sienori** [comment] 2018-05-13 07:11
@ponarC 
Does the problem occur with the new profile?
I restored 2000 tabs with a new profile with many sessions (over 100), but no problem occurred.

**Comment by ponarC** [comment] 2018-05-16 19:34
Yes it can be reproduced after killing FF

Result from clean profile (only TSM)
17 windows, 835 tabs - exported and imported in clean profile (my typical FF content)

No memory overhead and no 100% CPU usage. But visible page loading sequentially around 4-5 tabs per second.
I have to wait for all tabs loading because i don't know when popup next windows.
After few minutes FF ready to work.

After kill FF and open again this is typical reason when i need restore session (ff crash, no memory, computer crash)
FF instantly start restoring session (typically ask about that).
All windows and tabs created immediately but i noticed 100% CPU usage, freeze FF and visibly slowly memory grow (not to much to worry).
After few minutes FF ready to work.

Next kill and start
FF ask about restoring last session
Same as above
After few minutes FF ready to work (~5min cpu time). (memory peak ~40% and back to ~22%)

2,867.30 MB (100.0%) -- explicit
├──1,540.60 MB (53.73%) -- add-ons
│  ├──1,537.74 MB (53.63%) -- Tab-Session-Manager@sienori/window-objects
│  │  ├──1,535.90 MB (53.57%) -- top(moz-extension://3f4a1460-ac79-403d-8bbe-987ce104106c/_generated_background_page.html, id=12)
│  │  │  ├────782.83 MB (27.30%) -- active/window(moz-extension://3f4a1460-ac79-403d-8bbe-987ce104106c/_generated_background_page.html)
│  │  │  │    ├──782.68 MB (27.30%) -- js-compartment(moz-extension://3f4a1460-ac79-403d-8bbe-987ce104106c/_generated_background_page.html)
│  │  │  │    │  ├──782.45 MB (27.29%) -- classes
│  │  │  │    │  │  ├──776.06 MB (27.07%) -- class(Object)/objects
│  │  │  │    │  │  │  ├──649.33 MB (22.65%) -- malloc-heap
│  │  │  │    │  │  │  │  ├──502.38 MB (17.52%) ── slots
│  │  │  │    │  │  │  │  └──146.95 MB (05.13%) ── elements/normal
│  │  │  │    │  │  │  └──126.72 MB (04.42%) ── gc-heap
│  │  │  │    │  │  └────6.39 MB (00.22%) ++ (14 tiny)
│  │  │  │    │  └────0.23 MB (00.01%) ++ (4 tiny)
│  │  │  │    └────0.15 MB (00.01%) ++ (3 tiny)
│  │  │  └────753.07 MB (26.26%) -- js-zone(0x7f45d0f19000)
│  │  │       ├──744.18 MB (25.95%) -- strings
│  │  │       │  ├──681.29 MB (23.76%) ++ (1736 tiny)
│  │  │       │  ├───31.61 MB (01.10%) ── string(length=15, copies=1381055, "firefox-default")/gc-heap/latin1
│  │  │       │  └───31.28 MB (01.09%) ── string(length=8, copies=1366469, "complete")/gc-heap/latin1
│  │  │       └────8.89 MB (00.31%) ++ (11 tiny)
│  │  └──────1.84 MB (00.06%) ++ (2 tiny)
│  └──────2.86 MB (00.10%) ++ (9 tiny)
├────709.86 MB (24.76%) ── heap-unclassified
├────216.85 MB (07.56%) -- gfx
│    ├──216.04 MB (07.53%) ── heap-textures
│    └────0.81 MB (00.03%) ++ (5 tiny)
├────123.99 MB (04.32%) ++ window-objects
├────119.03 MB (04.15%) -- heap-overhead
│    ├───79.11 MB (02.76%) ── bin-unused
│    ├───39.19 MB (01.37%) ── bookkeeping
│    └────0.72 MB (00.03%) ── page-cache
├────104.01 MB (03.63%) -- js-non-window
│    ├───52.79 MB (01.84%) -- zones
│    │   ├──47.71 MB (01.66%) ++ zone(0x7f45e893c000)
│    │   └───5.08 MB (00.18%) ++ (4 tiny)
│    ├───39.04 MB (01.36%) ++ runtime
│    └───12.17 MB (00.42%) ++ gc-heap
└─────52.95 MB (01.85%) ++ (24 tiny)

Then go throught lot of tabs to force load content repeatdly shift+tab
Waiting for few min to load contend/cache/save session etc.
Reduced autosave in TSM to 1 min and wait 2 min

Then again kill FF and run.
Situation as above - 100% CPU, FF show all tabs (empty) and freeze, memory slowly grow.
After 5 min cpu time FF seams to be ready (i head first seconds from youtube) but then freeze again and noticed slowly memory grow up to 60%
After next 3.5 min FF really was ready (youtube start playing) and memory drop to ~25%

TEST END

Then kill FF again and back to restoring my original profile... (PC have power cut off)
Looks like last above
3.5 min for loading tabs (no memory issue, FF freeze)
few second ok
6.5 min for loading contend? (memory issue peak 95%, FF very slow)
back to normal 32% memory, FF work fine

8,498.50 MB (100.0%) -- explicit
├──7,450.14 MB (87.66%) -- add-ons
│  ├──7,443.31 MB (87.58%) -- Tab-Session-Manager@sienori/window-objects
│  │  ├──7,442.86 MB (87.58%) -- top(moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/_generated_background_page.html, id=18)
│  │  │  ├──3,893.23 MB (45.81%) -- active/window(moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/_generated_background_page.html)
│  │  │  │  ├──3,893.01 MB (45.81%) -- js-compartment(moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/_generated_background_page.html)
│  │  │  │  │  ├──3,892.84 MB (45.81%) -- classes
│  │  │  │  │  │  ├──3,890.20 MB (45.78%) -- class(Object)/objects
│  │  │  │  │  │  │  ├──3,274.99 MB (38.54%) -- malloc-heap
│  │  │  │  │  │  │  │  ├──2,461.63 MB (28.97%) ── slots
│  │  │  │  │  │  │  │  └────813.36 MB (09.57%) ── elements/normal
│  │  │  │  │  │  │  └────615.22 MB (07.24%) ── gc-heap
│  │  │  │  │  │  └──────2.63 MB (00.03%) ++ (9 tiny)
│  │  │  │  │  └──────0.17 MB (00.00%) ++ (4 tiny)
│  │  │  │  └──────0.22 MB (00.00%) ++ (3 tiny)
│  │  │  └──3,549.63 MB (41.77%) -- js-zone(0x7f104d116000)
│  │  │     ├──2,117.17 MB (24.91%) -- strings
│  │  │     │  ├──1,717.42 MB (20.21%) ++ (2325 tiny)
│  │  │     │  ├────153.67 MB (01.81%) ── string(length=15, copies=6713877, "firefox-default")/gc-heap/latin1
│  │  │     │  ├────153.55 MB (01.81%) ── string(length=8, copies=6708674, "complete")/gc-heap/latin1
│  │  │     │  └─────92.53 MB (01.09%) ++ string(length=71, copies=932955, "moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/replaced/undefined")
│  │  │     ├──1,400.70 MB (16.48%) ── unused-gc-things
│  │  │     └─────31.76 MB (00.37%) ++ (9 tiny)
│  │  └──────0.45 MB (00.01%) ++ top(moz-extension://6eb04b01-249e-4bcb-bd6f-9ce63038df7f/replaced/replaced.html?state=redirect&title=Index%20of%20/private/xnxx&url=http%3A//localhost/private/xnxx/&favIconUrl=http%3A//localhost/favicon.ico, id=131)
│  └──────6.83 MB (00.08%) ++ (10 tiny)
├────376.90 MB (04.43%) -- heap-overhead
│    ├──236.15 MB (02.78%) ── bin-unused
│    ├──139.79 MB (01.64%) ── bookkeeping
│    └────0.96 MB (00.01%) ── page-cache
├────202.08 MB (02.38%) -- gfx
│    ├──201.45 MB (02.37%) ── heap-textures
│    └────0.63 MB (00.01%) ++ (5 tiny)
├────167.54 MB (01.97%) -- js-non-window
│    ├───86.59 MB (01.02%) ++ zones
│    └───80.95 MB (00.95%) ++ (2 tiny)
├────154.18 MB (01.81%) ++ (25 tiny)
└────147.66 MB (01.74%) ++ window-objects

**Comment by SeanMcMillan** [comment] 2018-07-06 18:19
I had OOM/memory blowup problems on FF61/TSM3.1.2, and I was able to significantly reduce the memory usage by unchecking "Tab Lazy Loading". (I know that's the opposite of what it says.)

This was a mere 12 windows/143 tabs, resulting in 2 processes over 2GB each. (Task Manager by eyeball only, sorry.)

Perhaps there was some sort of change to tab restore in firefox recently?

**Comment by alyandon** [comment] 2018-07-07 01:53
Same here on FF 61 and latest TSM.  Only usable by unchecking lazy tab loading but that seems to surface another issue with tabs being restored to the wrong URLs when I select them.  When I select the tab, the correct URL is present but then it navigates away from that URL to the URL of another tab.  Very bizarre.

**Comment by varsanyim** [comment] 2018-07-09 08:21
@sienori I experiencing the Problem as well on a Windows 7 PC. Only 50 Tabs across 3 Windows, which used to be a opened in a pinch of an eye struggling now for over 15 minutes before I kill it. I can't reproduce the way I finally can open Firefox w/o opening all the Tabs (previous session opens automaticaly). 

Any help would appreciated. Thanks!

**Comment by sienori** [comment] 2018-07-09 11:06
I have not been able to reproduce this problem.
It will be helpful if you tell me how to reproduce in the following format.
```txt
## Steps to reproduce
<!-- Detailed steps to reproduce the problem. -->
1. Start Firefox with clean profile
2. Install Tab Session Manager
3. 
4. 

## Expected result
<!-- If you have any screenshot or screencast, it will help me more. -->

## Actual result
<!-- If you have any screenshot or screencast, it will help me more. -->

## Platform information
* Platform (OS): 
* Version of Firefox: 
* Version of Tab Session Manager: 
```

**Comment by sienori** [comment] 2018-10-28 17:44
I fixed the problem that increased memory usage when restoring session or closing a large number of tabs. 90390af
Also, I added option to use "discarded" property for lazy loading. 45719c3
Enabling this option will improve performance when opening tabs.

**Closed** 2018-11-08 13:20 UTC
Labels: bug, solved
