### ISSUE TITLE
Memory leak in Firefox 59

### ISSUE THREAD

**Issue by RebelliousX** [sienori/Tab-Session-Manager#203] opened 2018-03-14 23:14 UTC
Just updated Firefox 59 from 58.02, I noticed Firefox became unresponsive and is using over 2GB of ram, usually 500-700MB for the tabs I open.

I started Firefox in safe mode, with all addons disabled, no problems.

I started half of my addons, (binary search method) to quickly discover which addon caused the huge memory usage and unresponsiveness. In the end, it was Tab-Session manager.

To verify again, disabled all addons and left tab session manager enabled, restarted firefox, restored tabs and the issue is there again.

Enabled all addons except Tab Session manager, no problems.

Initially I thought it would be uBlock Origin, but it is not.

Edit: Exported all sessions as json file, deleted all sessions, deleted storage.js, then imported sessions. It seems that the issue is gone, but I noticed there is a spike of memory usage like +400MB for few seconds at start up then it goes back to normal, until the second restart. the issue remains. :(

I noticed though, that when opening task manager, and closing one of firefox's processes that has lots of ram usage, firefox becomes responsive and doesn't actually close!

**Comment by sienori** [comment] 2018-03-18 16:41
I fixed it! https://github.com/sienori/Tab-Session-Manager/issues/171

**Comment by RebelliousX** [comment] 2018-03-20 20:43
Well, it was solved in v3.0 but all sessions are gone, even when importing them from JSON file nothing shows up. :/

**Comment by sienori** [comment] 2018-03-21 19:35
Similar problem: https://github.com/sienori/Tab-Session-Manager/issues/210

**Comment by RebelliousX** [comment] 2018-03-21 23:36
@sienori Thanks for your hard work, I am closing this if you don't mind.

**Comment by TurnOffNOD** [comment] 2018-05-06 10:03
Hi, the problem comes back again after tab-session-manager's May 3, 2018 update, versin 3.1.1.
The problem is the same with @RebelliousX , except that my firefox with tab-session-manager eats over 6GB RAM instead of 2GB.

**Comment by TurnOffNOD** [comment] 2018-05-06 11:28
Firefox version: 59.0.3. My firefox is auto updated, I didn't notice my firefox version (58 or 59.0.2 or 59.0.3) before the bug appeared.
Tab-Session-Manager: version 3.1.1 (addon panel says that last update is May 3, 2018).
Operating System: Win 7, 64bit. I installed 8GB RAM with my computer.
All my addons:
![image](https://user-images.githubusercontent.com/2140029/39672447-bcfb6a90-515c-11e8-8a0f-6e56e33152ad.png)
Among them, Adboe Acrobat addon and both Avast addons are always disabled, I never use them.
Tab-Session-Manager is disabled after the bug appeared.
If Tab-Session-Manager is not disabled, simply open firefox-now there is the "new tab" tab, then History-Restore Previous Session, wait some time and the RAM will be eaten.

**Comment by kevinkk525** [comment] 2018-08-19 13:03
I encounter something like this since I updated my browser to 61.0.2 (could be that I skipped some versions as I was not using that PC for several weeks).
After that, restoring the last session firefox uses 6GB of RAM but after some time it gets down to 2GB (I have many tabs and windows opened). 
After some time of using firefox (or just leaving it in background) the used RAM rises to 6GB again and at that time, loading a website takes a minute and I have to close firefox because it is basically unusable.
The firefox memory usage analyzer clearly shows 3GB of RAM used by Tab Session Manager.

If you need more information, logs, ... please ask. Hopefully this problem can be solved.

**Comment by sienori** [comment] 2018-10-28 18:02
I fixed the problem that increased memory usage when restoring session or closing a large number of tabs. 90390af
Also, I added option to use "discarded" property for lazy loading. 45719c3
Enabling this option will improve performance when opening tabs.
 I think that this problem is solved in the latest version.

**Closed** 2018-10-30 06:02 UTC
Labels: bug, duplicate, solved
