### ISSUE TITLE
Session List is empty after 3.0.0 update

### ISSUE THREAD

**Issue by BB8Rolls** [sienori/Tab-Session-Manager#210] opened 2018-03-21 15:48 UTC
Hello,
I closed down my browser last evening and this morning the session list is empty. Looks like TSM was updated when I reopened the browser this morning. I am missing 3 manually saved and all of the auto saved.
Thanks

**Comment by sienori** [comment] 2018-03-21 15:55
Is the state of the session list A or B?

A. "There is no session" is displayed
![a](https://user-images.githubusercontent.com/29514424/37720888-97d33b04-2d6b-11e8-91f0-b957652644f6.PNG)
B. Nothing is displayed
![b](https://user-images.githubusercontent.com/29514424/37720911-a4855a6c-2d6b-11e8-8962-015f337cce14.PNG)

**Comment by BB8Rolls** [comment] 2018-03-21 15:58
Image B
Thanks for the speedy response!

**Comment by sienori** [comment] 2018-03-21 16:01
Please restart Firefox.

**Comment by BB8Rolls** [comment] 2018-03-21 16:09
I closed Firefox and reopened. No luck. 
Closed FireFox and rebooted. No luck

**Comment by sienori** [comment] 2018-03-21 16:12
Please open about:debugging.
Check "Enable add-on debugging" at the top of the page and click on Tab Session Manager Debug.
![1](https://user-images.githubusercontent.com/29514424/37721822-dce27bae-2d6d-11e8-8516-f59ec88c9fae.PNG)
![2](https://user-images.githubusercontent.com/29514424/37721832-e06315a4-2d6d-11e8-97f5-4d27f13f8cc2.PNG)

Open the "Console" tab of the development tool and tell me the logs shown there.
If possible, it will be helpful if you can take a screenshot. 
![180322_00](https://user-images.githubusercontent.com/29514424/37721862-f5083b56-2d6d-11e8-959a-69787e350dff.png)

Thanks for your cooperation.

**Comment by BB8Rolls** [comment] 2018-03-21 16:45
Thanks so much
Here you go
![console](https://user-images.githubusercontent.com/37629169/37723815-ac783480-2d05-11e8-961b-60452610bd56.png)

**Comment by sienori** [comment] 2018-03-21 16:51
Thanks!
Hmm, It seems to have failed in database initialization processing.
Please click "target" in the first line and tell me the logs.
Additional information should be displayed.

**Comment by BB8Rolls** [comment] 2018-03-21 16:59
Here you go
![console](https://user-images.githubusercontent.com/37629169/37724699-baa15f8a-2d07-11e8-9d09-808d9f49f18a.png)

**Comment by sienori** [comment] 2018-03-21 17:03
Please copy the value of "message" on line 7 and tell me.

**Comment by sienori** [comment] 2018-03-21 17:05
Also, please tell me the version of Firefox

**Comment by BB8Rolls** [comment] 2018-03-21 17:08
Line 7 = The operation failed for reasons unrelated to the database itself and not covered by any other error code.

Firefox ver 59.0.1 (64-bit)

**Comment by sienori** [comment] 2018-03-21 17:27
Thank you very much!
Please open "storage" tab.
What will be displayed when "Indexed Db" tree is opened?
![180322_01](https://user-images.githubusercontent.com/29514424/37726262-513de98e-2d78-11e8-8ac0-ea35eefd29f4.png)

**Comment by BB8Rolls** [comment] 2018-03-21 17:56
Thanks for stick with this
![storage](https://user-images.githubusercontent.com/37629169/37728055-aa8c6b5a-2d0f-11e8-9bb4-bcc9922ce4a1.png)

**Comment by sienori** [comment] 2018-03-21 17:58
OK, thanks.
I'd like to know if it is a problem specific to an extension.
Here is a sample of IndexedDB.
http://www.tohoho-web.com/html5/indexed_db_api_sample.html
Please click "Create" and check whether an error is output.

**Comment by BB8Rolls** [comment] 2018-03-21 18:29
Thanks!
---------------------------------------------------- 
START: createSample() 
END : createSample() 
ERROR: undefined:undefined

**Comment by boheme61** [comment] 2018-03-21 18:33
Hi , i have the exact same problem ... all my sessions are gone when open the browser today :( ... had 10 user-saved and 10 autosaved .... really need my usersaved ! :( ... could you guys try to rollback latest update ?
Regards JC

**Comment by boheme61** [comment] 2018-03-21 18:34
PS: its the only add-ons i have , so no coflict with other add-ons

**Comment by sienori** [comment] 2018-03-21 18:51
@BB8Rolls 
Thank you for your cooporation!

Please install version 2.1.1.
I think that sessions data has not disappeared.
https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/versions/

Unfortunately, It appears that your profile of Firefox has a cause.
Similar cases have been reported, but the solution has not been found.
https://bugzilla.mozilla.org/show_bug.cgi?id=944918

To solve fundamentally, reset the profile. (**Caution:** Addons and settings will be deleted.)
https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

I will continue to investigate this issue.

**Comment by BB8Rolls** [comment] 2018-03-21 19:03
2.1.1 brought saved sessions back. Thank you. I will export/back up my sessions and try the reset profile and let you know.

**Comment by ci5er** [comment] 2018-03-21 19:54
FWIW - I think it *is* saving sessions in storage.js (at least the auto-save stuff). The sail end of that json file had some pretty recent auto-save entries (even though I couldn't see any of them when the add-on popped up).

**Comment by BB8Rolls** [comment] 2018-03-21 22:11
So, after reverting to 2.1.1 I had my saved sessions return.
I back up the sessions and exported them just in case. Good thing I did. 
Completed the reset Firefox then reinstalled TSM. No sassions. Dang. Restored from back. YEA! all there. 
So far so good. All other add in back installed and TSM is 3.0.0 
Closed and opened Firefox a number of times. Rebooted and so far so good. If you try this, BACK UP your sessions first.

**Comment by ci5er** [comment] 2018-03-21 22:33
Thanks for relaying that closing note back.

I'm hoping that I can avoid the profile reset (because I'm both lazy and have a LOT of add-ons and about:config parameters that I've been toggling over the years), but given that the bug has been oustanding on the Mozilla end for over 4 years, I'm probably just going to have to bite the bullet this weekend... (Or stay with 2.1.1 forever!  :smile:

**Comment by Biggizen** [comment] 2018-03-21 23:00
I had the same problem with new v3. It was situation B shown in the second post. I solved it by switching "dom.indexedDB.enabled" in about:config from _false_ to _true_. After that the situation changed from B to A. So addon works again, but all sessions are gone. 

Fortunately I had made a backup of my 154 open tabs with the addon tab2txt before, so I was able to bring them back by using Tab Session Mannager's option to create a session from a list of URLs by copy-pasting them out of the saved txt-file.

**Comment by sienori** [comment] 2018-03-22 04:58
@BB8Rolls 
Thanks for the report!
You've been so helpful.

@Biggizen 
Interesting. I was able to reproduce the behavior.
Once you install version 2.1.1 and install version 3.0.0 again, the sessions will be restored.
I will continue to investigate.

**Comment by mwld** [comment] 2018-03-22 08:02
I was having the same problem B today after starting Firefox. When I recognized that the storage.js file (in {profile}\browser-extension-data\Tab-Session-Manager@sienori) was still intact I went here and found this issue topic.

Rolling back to 2.1.1 solves the issue. But installing 3.0.0 afterwards brings it back.

I'm using Firefox 59.0.1 (64-Bit) on Windows 10 (64-Bit).

**Comment by sienori** [comment] 2018-03-22 08:15
I found a solution apart from resetting the profile.

Please access ”about: profiles" and open the root directory.
![pro](https://user-images.githubusercontent.com/29514424/37758431-8d352ff8-2df3-11e8-8bf3-405f16d51257.PNG)


Please quit firefox and delete "storage" folder.
****Caution: Data on some add-ons and some of the services may be lost.
Please execute after understanding the risk.****
![z](https://user-images.githubusercontent.com/29514424/37758436-8f67d1e0-2df3-11e8-890d-5c4eaffe8aa5.PNG)

After that, once you install version 2.1.1 and install version 3.0.0 again, the sessions will be restored.

I am looking for someone to try this method.

**Comment by hackel** [comment] 2018-03-22 08:31
I got nervous when I read this report, but just wanted to report that after I was automatically upgraded to 3.0, all of my previously saved sessions are still showing up in Firefox 58.0.2.  Just in case there is an issue between the two versions.

**Comment by MrLent** [comment] 2018-03-22 09:13
@sienori 
Hi, I tried what you proposed in your last message (without going back to v2.1.1) and it works on FF 59.0.1 (Linux 64-bit).

**Comment by mwld** [comment] 2018-03-23 08:53
@sienori The suggested solution works! After deleting storage, installing 2.1.1 first and then 3.0.0 again the add-on is working as expected and my sessions are present. Thanks a lot!

**Comment by sienori** [comment] 2018-03-23 12:07
@MrLent @boheme61 @mwld 
Thanks for the report!
I posted a solution method.
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

I released version 3.0.1.
If an error occurs, a link to the solution will be displayed.

**Comment by irvinm** [comment] 2018-03-25 02:41
@sienori, with the change to IndexedDB, how does a user backup their sessions from the file system for offline backups with the idea of being able to restore if something gets corrupted?  In the past, I just ran a scheduled script every hour to backup storage.js in case there were any problems.  

I know you have the option to back things up when the browser starts, but that might only be once a day or every 3 days.

**Comment by brunoais** [comment] 2018-03-25 08:36
You may backup the storage directory instead. All IndexedDB databases are
in there.
You can try searching for the specific database file if you want to.

**Comment by irvinm** [comment] 2018-03-25 19:53
Thanks @brunoais. I have been looking into how IndexedDB is used and information stored. 

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

This talks about the storage aspects and it looks like TSM is stored at:

- "profile"/storage/default

In my case:

- "profile"/storage/default/moz-extension+++3a2bd676-ce47-4d4c-9e87-3865c0c81d7f

It looks like the individual sessions (they are not clear text) are located:

- "profile"/storage/default/moz-extension+++3a2bd676-ce47-4d4c-9e87-3865c0c81d7f/idb/1782160246ssensosi.files

My concern is that backing up the root addon storage directory is probably only good for the installed instance of TSM due to how the data is probably tied into different aspects of that installation.  I doubt zipping that folder and dropping into a fresh (or repaired) install will work.

I have a feeling the only true way to backup the data is via the "startup backup" or "manual export" as that is just plain JSON that can be imported back into any installation.  I would either like to make backups myself on some schedule (automated at the file system level) or be able to backup my data more regularly in an automated way within the addon itself.  [I sometimes go 1-5 days between restarting Firefox]

**Comment by brunoais** [comment] 2018-03-25 20:41
The `3a2bd676-ce47-4d4c-9e87-3865c0c81d7f` part you see there is tied to the extension id. Extensions cannot change id, so that one's stable.
The `*.files` directories always only contain temporary data. They are safe to ignore.
The files you must backup are the `*.sqlite` files.
Additionally, if there are any `*.sqlite-wal` or `*.sqlite-shm`, you should pause and wait until they are deleted and then copy the the corresponding `*.sqlite` file. If firefox is not running, you may just copy the 3 types of files for each one.

When I used FEBE, I used to have the backups for myself automatically. Currently, I'm still searching for an alternative....

**Comment by auipga** [comment] 2018-04-05 15:42
> Step 3: Please quit firefox and delete "storage" folder.

In my case it was enough to delete the following in `storage/default/`:

- `https+++*^userContextId=5` where * is (in my case) `amazon.de` and `youtube.com`
- `https+++www.xing.com`

The error comes back if I restore at least one of these three folders.
Maybe this helps you to figure out a more specific reason.

**Comment by L1X1** [comment] 2018-10-28 07:52
Hi,
I've been using TSM for a while now and at some point when I clicked on the icon to open it, it would bring up the session list except it would be the same as the image B you've shown, but then it would make the whole session list window become blank. At first I just thought that it was loading the sessions because I have a lot because of the auto save, but I left it open for a few hours and it was still blank, so I'm not sure if this is a similar issue that BB8Rolls had, but it is constantly preventing me from using TSM.
(This what it looked like.)
![untitled](https://user-images.githubusercontent.com/44541710/47613387-20093480-dada-11e8-9b91-7a0f3553d13e.jpg)

**Comment by grahamperrin** [comment] 2018-10-28 12:05
### Firefox Storage Test

- https://firefox-storage-test.glitch.me/

@L1X1 what's reported by the test?

What's your operating system?

**Comment by L1X1** [comment] 2018-10-28 23:17
Sorry grahamperrin, I'm not really sure what to do about the storage test, I clicked on the link, but nothing really happened other than it saying that it was a testing ground and I'm using windows 10.

**Comment by grahamperrin** [comment] 2018-10-29 15:08
> nothing really happened

Did it not present an overview (whether storage is working)?

And specific statuses for the four subsystems?

**Comment by L1X1** [comment] 2018-11-02 00:28
Okay so I tried again just now and it brought up the things you were asking about.
![capture](https://user-images.githubusercontent.com/44541710/47887240-037a4d00-de8a-11e8-857d-440c3a9c1f63.JPG)

**Comment by RobertAb1** [comment] 2019-01-04 04:21
@BB8Rolls @boheme61 @ci5er @L1X1 @Biggizen @mwld @auipga @brunoais @irvinm @hackel _and others_

Vote on Bug 944918, Bug 1423917, Bug 1427928 _and other bugs_ on Bugzilla@Mozilla website to speed up solving this issue by Mozilla and removing this problem (_and other issues_) from TSM: #150

**Comment by RobertAb1** [comment] 2019-04-02 16:33
@sienori 
[Bug 1423917](https://bugzilla.mozilla.org/show_bug.cgi?id=1423917) was fixed.

**Closed** 2020-12-09 09:16 UTC
Labels: Firefox's bug, solved

**Comment by yonofu12345** [comment] 2023-07-04 13:01
IndexedDB is not available in your browser.
and all my previously saved tabs are gone. How can I restore them?
windows11
Microsoft EDGE
Tab Session Manager
Version 6.12.1

**Comment by kurosawa12345** [comment] 2026-05-01 09:11
The same thing happened to me.
Has anyone managed to get rid of it?

**Comment by yonofu12345** [comment] 2026-05-02 11:42
The chat has closed, so could you send me the chat history?
