### ISSUE TITLE
Restoring

### ISSUE THREAD

**Issue by pranavsshah** [sienori/Tab-Session-Manager#250] opened 2018-05-10 14:17 UTC
Hello,
I was using Firefox 59.2 then i updated the version to Firefox 60.0
and when i checked the TSM was blank and I was getting this error
I checked and tried even to restore it from the earlier session (which are 22 in no.) but i do not know where they are stored and how do i get them or load them
Can anybody please help me how to go about it and restore my session?
![tsm error](https://user-images.githubusercontent.com/29746735/39874269-f53c6e6e-548a-11e8-8bd8-db4e6e2e0daf.jpg)

**Comment by sambul13** [comment] 2018-05-22 16:52
But how to restore previous sessions after that?

**Comment by mkvcd** [comment] 2018-05-28 18:37
Here's how I fixed this problem. Today, when I opened Tab Session Manager, once again I saw the error (I'd happened once before). The first time I was able to restore my sessions by following the instructions the author provided when the error (IndexDB is not available in your browser.) appeared on the add-on. This time around though, I couldn't do that. I installed the version 2.1.1 as suggested by the author, no luck. There were no sessions. Then again I installed the updated version still nothing happened. Finally, after searching for an answer to restore the session, this is what worked. So in the solution the author tells you to delete the folder "storage", so first I copied that folder on my desktop, and then deleted it. So I still had it. 

First, I removed the add-on and reinstalled it. Then, I went to the "storage" folder on my desktop, which I copied and pasted before deleting it. Inside the folder I clicked default > moz-extension+++d7e4a818-2cc1-429d-85ac-1769fd1f69b7 > idb. And then I copied this file: "1782160246ssensosi.sqlite". I typed about:profiles in the address bar, and on that page, I opened root directory folder. I clicked storage > default > moz-extension+++d7e4a818-2cc1-429d-85ac-1769fd1f69b7 > idb. Inside the idb folder I pasted the file I copied from my desktop (1782160246ssensosi.sqlite). In firefox, when I opened Tab Session Manager, my sessions were restored.

Note: Once you close and restart your browser, the sessions might be gone again. So do this: click on the gear icon inside Tab Session Manager > Click on "Sessions" > In Export Sessions, click "Export". 

Now, remove the add-on again, and reinstall it. Click on the gear icon inside  Tab Session Manager > Click on "Sessions" > In "Import Sessions", click browse and import the session that you exported before.

**Comment by sambul13** [comment] 2018-05-29 01:48
Thanks for sharing. But Firefox updated every few days, especially beta and other test versions. The extension author should have provided a reliable solution to this, not the nightmare like you described. There's Backup option the extension settings, but it doesn't backup automatically, at least in FF beta.

_Save backup
When Firefox starts up, create a backup file of sessions and save it in the download folder._

**Comment by sienori** [comment] 2018-06-07 07:14
Does that mean that IndexedDB error now appears in firefox version upgrade?
In the [wiki](https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error) I wrote, I did not consider that case.

In version 3 and later, sessions are stored in the storage folder.

If an IndexedDB error is displayed when updating from `version 2` to `version 3`, deleting the storage folder does not delete the sessions. Because in `version 2` the sessions are saved elsewhere.

However, if you are already using `version 3`, deleting the storage folder also deletes the sessions.

IndexedDB errors are caused by [firefox bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=944918).
It is known that it can be solved by deleting the cause file in the storage folder.

I must apologize that the description on the wiki was wrong. 
If you are already using `version 3`, **do not delete the storage folder**.
I will fix the wiki soon.

**Comment by sienori** [comment] 2018-06-07 07:35
Same issue: https://github.com/sienori/Tab-Session-Manager/issues/239

**Comment by sambul13** [comment] 2018-06-08 14:33
> It is known that it can be solved by deleting the cause file in the storage folder.
Can you be MORE specific: which file we should delete?

**Comment by sienori** [comment] 2018-06-08 15:53
@sambul13 
I updated the wiki. https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
>**Restore other data**
The storage folder stores data of other add-ons and services. If you want to restore them, please copy the folder of each service to the storage folder in the same way as in the example above.
IndexedDB error occurs when a corrupted file exists in the storage folder. It is necessary to restore it by excluding corrupted files.
Please Copy folders one by one and check whether IndexedDB error occurs each time. You can identify currupted files.

To migrate sessions to version 2, export sessions from the settings page.
After that please install version 2 and import sessions.

There is a problem that data is suddenly lost to StorageAPI used in version 2. https://github.com/sienori/Tab-Session-Manager/issues/153
I recommend using version 3.

> Your extension fails every day with almost daily FF beta updates

It is highly likely that there is a problem with your firefox profile.
I think it will be resolved by resetting the profile.

I apologize for any inconvenience.

**Comment by RobertAb1** [comment] 2019-01-04 04:31
@pranavsshah @bnvis @sambul13 @mkvcd  _and others_

Vote on Bug 944918, Bug 1423917, Bug 1427928 _and other bugs_ on Bugzilla@Mozilla website to speed up solving this issue (with broken indexedDB) by Mozilla and removing this problem (_and other issues_) from TSM: #150

**Closed** 2019-01-04 05:10 UTC
Labels: duplicate
