### ISSUE TITLE
Sessions have "disappeared" - blank list

### ISSUE THREAD

**Issue by echdareez** [sienori/Tab-Session-Manager#724] opened 2021-03-11 12:41 UTC
## Short description
After restarting my Chrome this morning, all the sessions that were present (about 60 as I have periodic backups and quite a lot of manual saved ones) have disappeared. 
Something else : when I now save 2 (or more) sessions manually and reopen the overview, only the last one is visible/shown. Had a look around and the sessions (old ones and the ones I saved after they disappeared) are still present here : c:\Users\echdarees\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\chrome-extension_iaiomicjabeggjcfkbimgmglanimpnae_0.indexeddb.blob\1\25\

Full transparency : I did fiddle with one session this morning : as I wanted an easy way to change to change the extension ID of The Great Suspender (to the one of The Marvellous Suspender), I did the following : save the session, added a tag to the saved session, quit Chrome, found the corresponding file of that session using that tag, opened this file in HxD and changed the ID's (old to new). They are the same length (in place edit and no file size change) and I've done this before a month ago so I'm not sure if this is related? 

![image](https://user-images.githubusercontent.com/80462163/110788795-61e04300-826f-11eb-9620-b0bb4475e794.png)

## Platform information
* Platform (OS): Windows 10 - 20H2 - build 19042.804
* Version of browser: 89.0.4389.82
* Version of Tab Session Manager: 6.4.1
 
## Steps to reproduce
I can not reproduce the problem - if I start from a clean profile (deleting my Chrome folder and so on...), it seems to work fine. 

## Expected result
Recovery of my previous sessions. 

## Actual result
I found the option to enable the debug log (not sure where this is saved though) but I can certainly have a look around if there's something that needs to be checked :-) 

## Additional context
Nothing further to add at this moment. Thanks!

**Comment by sienori** [comment] 2021-03-11 14:11
I think the problem is probably caused by updating files by HxD. If you want to edit the contents of the session, it is safer to export the session as json, edit it, and then import it.

It is strange that only the last session is shown. You can determine if a session exists internally by looking at the log. See the [wiki](https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode) for how to use the debug mode.

**Comment by echdareez** [comment] 2021-03-11 14:34
Thanks a lot for the speedy response! And the help :-)  

So : about that edit with HxD : it might be indeed that this caused the issue but I had to use HxD as the procedure you describe, never worked for me. Or I might do something wrong? 
I go here : 
![image](https://user-images.githubusercontent.com/80462163/110802238-4af51d00-827e-11eb-8f1f-cc2049cefd3e.png)
And after that, I try to do this : 
![image](https://user-images.githubusercontent.com/80462163/110802281-55171b80-827e-11eb-8d65-29f575a5b6ef.png)
So... a "read failed"...  But it's strange that the HxD did work ok a month ago... I even used it 3 times on 3 different sessions (as some tabs had different ID's of different TGS builds) and never experienced an issue. Oh well... 

And again thanks for the pointer : not much experience with Chrome Devtools but I had a look : 
saved a session, closed TSM and reopened it and got this : 
![image](https://user-images.githubusercontent.com/80462163/110802848-dff81600-827e-11eb-9d15-72d3312a299e.png)

Tried to dig around (with my limited knowledge of this) and found this : 
![image](https://user-images.githubusercontent.com/80462163/110802977-0322c580-827f-11eb-94f7-8287603173a8.png)

So : it does find 30 sessions? 

I'll try to uninstall + reinstall TSM later on, if that fixes the problem and my sessions are properly saved, I'll just settle with that solution :-)   But thanks again for your help!

**Comment by echdareez** [comment] 2021-03-11 14:41
So : after an uninstall + reinstall of TSM, it seems to work ok again : 
![image](https://user-images.githubusercontent.com/80462163/110804000-0d918f00-8280-11eb-887b-0df631040160.png)

If it's fine for you, I can close this incident? Or I can leave it open if you need to troubleshoot this? (I took a backup of my profile, just in case)

**Comment by sienori** [comment] 2021-03-11 15:06
Ok, I close this issue. Thanks!

**Closed by sienori** 2021-03-11 15:06 UTC
Labels: Sessions lost
