### ISSUE TITLE
Can you add the feature to save Tab Groups?

### ISSUE THREAD

**Issue by Hamakaze1s** [sienori/Tab-Session-Manager#732] opened 2021-03-25 05:58 UTC
Link to the introduction of this function
https://support.google.com/a/users/answer/10392467?hl=en

I hope to save the information of the group for recovery

**Comment by Pictor13** [comment] 2021-04-08 21:46
I also want it; but I'd close this issue: it is a duplicate of #652

**Comment by sienori** [comment] 2021-04-18 14:53
In version 6.6.0, I implemented support for tab groups! https://github.com/sienori/Tab-Session-Manager/commit/f3e14f7d30ec9e46a58d6a84848f6a4b677a7591
To save tab groups, you need to install [an additional extension](https://github.com/sienori/Save-Tab-Groups-for-Tab-Session-Manager).

**Closed** 2021-04-18 14:53 UTC
Labels: duplicate, enhancement, solved
