### ISSUE TITLE
[Feature] Restore window names on browser windows restore

### ISSUE THREAD

**Issue by placidocean** [sienori/Tab-Session-Manager#973] opened 2022-04-04 20:10 UTC
**Is your feature request related to a problem? Please describe.**
I am using several browser windows to keep generic/ad hoc/programming/gaming page sets I use for prolonged time and on several virtual desktops dedicated to activities. Browser's windows are properly named and placed on related virtual desktops. When there is a need for reboot, browser window's names are lost and it is tedious to restore names.

**Describe the solution you'd like**
It would be a great if Tab Session Manager will restore windows names when restore browser's windows.

**Describe alternatives you've considered**
It would be also great if somebody point me to existing settings I missed so window's names can be restored. And if on restoration windows will be placed on virtual desktop they are was on session store, it would be perfect.

**Additional context**
I am using Windows 10, Chrome  and of course Tab Session Manager.

**Comment by adamkerz** [comment] 2022-09-13 06:46
There are a bunch of pull requests outstanding, some really simple - I would look at creating a PR if I was fairly confident that it would get reviewed and merged, but I'm not that confident right now. @sienori can you comment?

**Comment by adamkerz** [comment] 2022-09-13 07:04
With regard to this, STILL looks like the WebExtensions API does not yet support Window Naming: https://bugs.chromium.org/p/chromium/issues/detail?id=1190160

Suggest close this one as a duplicate of #770

**Comment by placidocean** [comment] 2022-09-13 15:44
duplicate of https://github.com/sienori/Tab-Session-Manager/issues/770

**Closed** 2022-09-13 15:44 UTC
