### ISSUE TITLE
Auto save doesn't work

### ISSUE THREAD

**Issue by xarx00** [sienori/Tab-Session-Manager#276] opened 2018-07-18 14:28 UTC
## Short description
No new auto-save sessions occur in the session list.

## Steps to reproduce
1. Turn on TSM > Settings > AutoSave, and set interval to 15 minutes
2. Use FF for some time, at least 30 mins
3. Click the TSM toolbar icon to check whether new sessions were created automatically

## Expected result
Every 15 minutes, a new session should be created

## Actual result
No session is created automatically

## Platform information
* Platform (OS): Windows 7 Pro x64
* Version of Firefox: 60.1.0 ESR x64
* Version of Tab Session Manager: 3.2.0

**Comment by sienori** [comment] 2018-07-18 14:55
Please restart firefox.
I have confirmed the problem that it will not work properly Immediately after installation.

**Comment by xarx00** [comment] 2018-07-18 20:13
Indeed, after FF restart everything starts to work. Thank you.

**Comment by ItielMaN** [comment] 2018-07-22 12:55
I'm using TSM for a pretty long time with the Auto Save function enabled, and this is not working for me (and I'm restarting Nightly on a daily basis when I'm requested by the update notification).
Using Windows 10 x86, lateset Nightly, TSM version 3.2.0.
"Save the session regularly" enabled, Interval set to 15, Maximum number Saved set to 100000, "Save the session when window was closed" enabled.

There was a time where TSM did actually autosave the session, but only for 20 times (10 regularly and 10 Window was closed).

**Comment by sienori** [comment] 2018-10-07 18:52
This problem was fixed in version 4.

@ItielMaN 
It seems that you are talking about another problem. 
If the problem is not solved, please make a new issue.

**Closed** 2018-10-07 18:52 UTC
Labels: bug, solved
